# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets_register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_of_disposal', models.CharField(blank=True, choices=[('sl', 'Sale'), ('dn', 'Donation'), ('ls', 'Loss')], max_length=2, null=True)),
                ('reason', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('dsp', 'Disposed'), ('emk', 'Earmarked')], default='emk', max_length=3)),
                ('disposal_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('disposal_currency', models.CharField(blank=True, choices=[('KES', 'Kenya Shillings'), ('USD', 'US Dollars'), ('GBP', 'Great Britain Pounds')], default='KES', max_length=5)),
                ('disposal_age', models.DecimalField(decimal_places=2, max_digits=4)),
                ('date_disposed', models.DateField(null=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assets_register.Assets')),
            ],
        ),
    ]
