# Generated by Django 2.2 on 2019-08-17 09:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetMakes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_make', models.CharField(db_index=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AssetModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.CharField(db_index=True, max_length=20)),
                ('asset_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets_register.AssetMakes')),
            ],
        ),
        migrations.CreateModel(
            name='AssetOwners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(db_index=True, max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, db_index=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('tel_no', models.CharField(max_length=15)),
                ('nature', models.CharField(choices=[('loc', 'Local'), ('int', 'International')], default='loc', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='AssetUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=40)),
                ('office_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets_register.Offices')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets_register.AssetOwners')),
            ],
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True)),
                ('asset_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('status', models.CharField(blank=True, choices=[('fnc', 'Functional'), ('fty', 'Faulty'), ('dps', 'Disposed'), ('emk', 'Earmarked for Disposal')], default='fnc', max_length=3)),
                ('date_of_purchase', models.DateField(default=django.utils.timezone.now)),
                ('warranty_end_date', models.DateField(null=True)),
                ('purchase_value', models.FloatField(default=0.0)),
                ('purchase_currency', models.CharField(blank=True, choices=[('KES', 'Kenya Shillings'), ('USD', 'US Dollars'), ('GBP', 'Great Britain Pounds')], default='KES', max_length=5)),
                ('expected_life', models.DecimalField(decimal_places=2, default=5, max_digits=4)),
                ('status_of_usage', models.CharField(choices=[('iss', 'In Use'), ('uis', 'In Store'), ('dsp', 'Disposed')], db_index=True, default='uis', max_length=3)),
                ('asset_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets_register.AssetModels')),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets_register.AssetTypes')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets_register.AssetOwners')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets_register.Vendors')),
            ],
        ),
        migrations.AddField(
            model_name='assetowners',
            name='custodian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets_register.AssetUsers'),
        ),
        migrations.AddField(
            model_name='assetmodels',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets_register.AssetTypes'),
        ),
        migrations.CreateModel(
            name='AssetIssuanceRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('comment_on_issue', models.CharField(blank=True, max_length=500, null=True)),
                ('returned', models.BooleanField(blank=True, default=False)),
                ('date_returned', models.DateField(null=True)),
                ('comment_on_return', models.CharField(blank=True, max_length=500, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets_register.Assets')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets_register.AssetUsers')),
            ],
        ),
    ]
