# Generated by Django 2.2 on 2020-07-03 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets_register', '0002_auto_20190922_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetUsersDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_still_staff', models.BooleanField(default=True, verbose_name='Still in the organization?')),
            ],
        ),
        migrations.CreateModel(
            name='NonHumanUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets_register.Offices')),
            ],
        ),
        migrations.AddField(
            model_name='assetmodels',
            name='model_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='assettypes',
            name='type_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='assetissuanceregister',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assetowners',
            name='custodian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assetowners',
            name='owner_name',
            field=models.CharField(max_length=30, verbose_name='Which department owns the asset'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='status',
            field=models.CharField(blank=True, choices=[('functional', 'Functional'), ('faulty', 'Faulty'), ('disposed', 'Disposed'), ('to be disposed', 'Earmarked for Disposal')], default='fnc', max_length=30),
        ),
        migrations.AlterField(
            model_name='assets',
            name='status_of_usage',
            field=models.CharField(choices=[('issued', 'In Use'), ('in store', 'In Store'), ('disposed', 'Disposed')], db_index=True, default='uis', max_length=10),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='nature',
            field=models.CharField(choices=[('local', 'Local'), ('international', 'International'), ('donor', 'Donor')], default='loc', max_length=3),
        ),
        migrations.DeleteModel(
            name='AssetUsers',
        ),
        migrations.AddField(
            model_name='assetusersdetails',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets_register.AssetOwners'),
        ),
        migrations.AddField(
            model_name='assetusersdetails',
            name='office_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets_register.Offices'),
        ),
        migrations.AddField(
            model_name='assetusersdetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
